### ISSUE TITLE
Normalise CSS

### ISSUE THREAD

**Issue by Ryuno-Ki** [nko5/modulus-demo#2]
For dark themed Firefox running on GNU/Linux, the default background color of `<body>` is some darkish gray. Therefore I'd recommend to set

``` css
body {
    color: black;
    background-color: white;
}
```

in your main.css (There are several stylesheets for normalising behaviour out there, too).
